spring.application.name=email-generator


gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=

# Your actual API key
gemini.api.key=AIzaSyCzp7waELdfxzr1K7Jr822AT1K6G4mMCLc