spring.application.name=email-generator


gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# Your actual API key
gemini.api.key=AIzaSyBYVE1Dt3CtgkMhEwQ4chRH2dy_s8MpgXQ

server.port=${PORT:8080}